name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REPOSITORY: ghcr.io/devgine
  IMAGE: symfony-golden
  VERSION: ${{ github.ref_name }}

jobs:
  publish:
    name: Build and Push
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v3'

      - name: Set up Depot CLI
        uses: 'depot/setup-action@v1'

      - name: Login to GitHub Container Registry
        uses: 'docker/login-action@v1'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPOSITORY_TOKEN }}

      - name: Set Version
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          echo "IMAGE_VERSION=${VERSION:1}" >> $GITHUB_ENV

      - name: Process builder
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          echo "build_version=preprod" >> $GITHUB_ENV
          echo "my_docker_image=$REPOSITORY/$IMAGE:$IMAGE_VERSION,$REPOSITORY/$IMAGE:latest" >> $GITHUB_ENV
          echo "build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Process builder
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          echo "build_version=dev" >> $GITHUB_ENV
          echo "my_docker_image=$REPOSITORY/$IMAGE:dev" >> $GITHUB_ENV
          echo "build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: 'depot/build-push-action@v1'
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          push: true
          tags: ${{ env.my_docker_image }}
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ env.build_date }}
            BUILD_VERSION=${{ env.build_version }}
